### ISSUE TITLE
aurproxy doesn't run on newer Mesos clusters.

### ISSUE THREAD

**Issue by derekslager** [tellapart/aurproxy#39]
The assembled Docker image doesn't include libraries which are necessary on newer Mesos clusters, see AURORA-1487. Without these, startup fails:

`Could not load MesosExecutorDriver!`

**Comment by derekslager** [comment]
https://github.com/tellapart/aurproxy/pull/40

**Comment by ThanosBaskous** [comment]
Thanks! Merged.
