### ISSUE TITLE
Allow HEAD requests for HttpHealthCheckShareAdjuster

### ISSUE THREAD

**Issue by SEJeff** [tellapart/aurproxy#4]
Depending on the application, HEAD can return less data than a GET request as hardcoded in this share adjuster with `requests.get`.

**Comment by ThanosBaskous** [comment]
On board. An optional 'method' or 'verb' parameter with a default value of 'GET' would maintain compatibility for existing users.

**Comment by SEJeff** [comment]
This is fixed by #11

**Comment by ThanosBaskous** [comment]
Thanks @SEJeff!
