### ISSUE TITLE
HTTP 2 support?

### ISSUE THREAD

**Issue by Citrullin** [tellapart/aurproxy#42]
Hi,
I evaluating load balancing solution on mesos, especially, aurora. I'm using grpc. My question is simple: Does aurproxy support http 2?

**Comment by ThanosBaskous** [comment]
Hi @Citrullin, thanks for your question.

aurproxy is currently set up to use (and has been tested with) nginx 1.9.0 (see Dockerfile), which doesn't support HTTP/2 (it [looks like](https://www.nginx.com/blog/nginx-1-9-5/) HTTP/2 support was introduced in 1.9.5).

That being said, aurproxy should work fine with newer versions of nginx. Besides building/using a newer version of nginx, I think that the nginx template at templates/nginx/nginx.conf.template would have to be modified to [specify "http2"](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-16-04) on the listener line.

**Comment by Citrullin** [comment]
Thanks @ThanosBaskous for your answer. I will check it.
